#!/bin/bash
#
# "looma" script to be run on reverse SSH server
#     see help() below for paramaters

help () {
  echo "usage:"
  echo "  looma               [same as 'looma help']"
  echo "  looma help          [explains options]"
  echo "  looma ports         [list ports with tunnels to remote Loomas]"
  echo "  looma remotes       [list connected remote Loomas by ID]"
  echo "  looma access port <port-number> [login to a remote looma by port number]"
  echo "  looma access <ID>   [login to a remote looma by ID]"
  echo "  looma info <ID>     [retrieve 'info' file from remote looma]"
  echo "  looma addremote <ID>    [add a new remote looma]"
  echo "  looma deleteremote <ID> [delete a remote looma]"
  exit
}

getID () {
  # look up remoteID for $port
    #ID=$(netstat -antp | grep "127\.0\.0\.1:$port" | sed -p 's/sshd: \(.*\)/\1/p')
  ID=$(sudo netstat -antp | grep "127\.0\.0\.1:$port" | sed -n 's/.*sshd: \(.*\)/\1/p')
  echo "ID for port $port is $ID"
}

getport () {
  # look up port # for $ID
  #port=$(netstat -antp | grep "127\.0\.0\.1.*sshd: $ID" | sed -p 's/127\.0\.0\.1:\([0-9]{5}\)/\1/p')
  port=$(sudo netstat -antp | grep "127\.0\.0\.1.*sshd: $ID" | sed -n 's/.*127\.0\.0\.1:\([0-9][0-9][0-9][0-9][0-9]\).*/\1/p')
  if [[ ! $2 = "quiet" ]]
  then
     echo "port for remoteID $ID is $port"
  fi
}

checkID () {
  # verify that $1 is a legal remoteID (format is "rxxxx")
  regex="r[0-9]{4}"
  if [[ ! $1 =~ $regex ]]
   then
     echo "$1 is not a legal remoteID. must be format 'rxxxx'"
     exit
 fi
}

info () {
  ID=$1
#  checkID $ID
  getport $ID
  echo "retrieving info from remote Looma $ID on port $port"

  # get from remote Looma: /var/www/html/info file contents, Looma Version, and archivetimestamps for code and content

  scp -q -P $port -i ~/.ssh/$ID-id_rsa "odroid@127.0.0.1:/var/www/html/info" /dev/stdout
  echo -n "    Looma version:      "
  scp -q -P $port -i ~/.ssh/$ID-id_rsa 'odroid@127.0.0.1:/var/www/html/Looma/includes/looma-version'  /dev/stdout

  scp -q -P $port -i ~/.ssh/$ID-id_rsa 'odroid@127.0.0.1:/var/www/html/Looma/archivetimestamp.txt'    /tmp/timestamp
  timestamp=$(cat /tmp/timestamp)
  echo -n "    Last code update:    "
  date --date="@$timestamp"   "+%F %T"

  scp -q -P $port -i ~/.ssh/$ID-id_rsa 'odroid@127.0.0.1:/var/www/html/content/archivetimestamp.txt'  /tmp/timestamp
  timestamp=$(cat /tmp/timestamp)
  echo -n "    Last content update: "
  date --date="@$timestamp"   "+%F %T"
}

ports () {
  sudo netstat -antp | grep 127.0.0.1:[0-9][0-9][0-9][0-9][0-9]
  exit
}

remotes () {
#  echo "these remote IDs are in use:"
  cat /etc/passwd | grep ^r[0-9]* | sed -n  's/.*\/home\/\(r[0-9][0-9][0-9][0-9]\).*/\1/p' | while read ID; do getport $ID quiet; echo "$ID:$port"; done

#  cat | grep | sed | while read ID; do getport $ID; echo "$ID:$port"; done

  exit
}

access_by_port () {
  getID $port
  ssh -p $port -i ~/.ssh/$ID-id_rsa odroid@127.0.0.1
  exit
}

access_by_ID () {
  checkID $ID
  getport $ID
  ssh -p $port -i ~/.ssh/$ID-id_rsa odroid@127.0.0.1
  exit
}

addremote () {
  checkID $ID
  sudo  reversessh -a $1
  exit
}

deleteremote () {
  checkID $ID
  reversessh -r $1
  exit
}

case $1 in

  help | "")
    help
    ;;

  info)
    ID=$2
    info $ID
    ;;

  ports)
    ports
    ;;

  remotes)
    remotes
    ;;

  addremote)
    ID=$2
    addremote $ID
    ;;

  deleteremote)
    ID=$2
    deleteremote $ID
    ;;

  access)
    case $2 in

      port)
      port=$3
      access_by_port $port
      ;;

      *)
      ID=$2
      access_by_ID $ID
        ;;
    esac
    ;;

  *)
    help
    ;;
esac