#!/bin/bash
#
#  filename: loomaarchive
#       author: skip
#       date:   Aug 2019,
#               OCT 2020 - changed to --size-only for CONTENT upload
#                           to avoid unnecessary updates to modification date stamps for content files, so that download RSYNC will continue to skip them
#               OCT 2023 - added 'archivetimestamp.txt' file to archive for use by 'loomaupdate'
#
#  used to update the 'archive' version of Looma on rsync.net, including new code, database & content
#
#  set up to run on a MAC [other computer types would require changes to this script]

#RSYNC options used:
#-a  "archive" equivalent to -rlptgoD
#   -r  recursive
#   -l  recreate symlink on the destination
#   -p  preserve permissions
#   -t  preserve modification time
#   -g  preserve group
#   -o  preserve owner
#   -D  transfer devices and specials (NA for Looma)

#-vv	very verbose
#-z  	use compression
#--dry-run
#--delete 	delete files on destination that are not on source
#--perms (=== -p)
#--update
# --include ".ssh/"  --exclude ".[!.]*" --delete-excluded
result () {
    if [[ $1 -ne 0 ]]
    then
        echo "****************************************************************"
        echo "ERROR: previous operation returned $1"
        echo "****************************************************************"
        echo "it is recommended to RETRY loomaarchive"
        exit
    else
        echo "****************************************************************"
        echo "operation successful"
    fi
}  #  end result()

timestamp () {  # $1 is the dir to put the timestamp in [content or Looma]
  date +"%s" > $1/archivetimestamp.txt
  echo " - - setting "$1/archivetimestamp.txt to $(date +"%s")
  echo "************************************"
}  #  end timestamp()

echo "************************************"
echo " - - setting database version to today's date"
echo "************************************"
mongosh looma < "/usr/local/var/www/Looma/looma shell scripts/loomaMongoSetDate" &>/dev/null

if [[ ! -d /usr/local/var/www/Looma/mongo-dump ]]
then
    mkdir /usr/local/var/www/Looma/mongo-dump
fi

cd /usr/local/var/www/Looma/mongo-dump  # cd to mongo dumps folder (on a MAC)
if [ -d dump ]
        then
            echo " - - moving previous mongo dump to ~/Desktop/LoomaMongoDumps/"
            echo "************************************"
            now=$(date '+%Y-%m-%d')
            rm -R    ~/Desktop/LoomaMongoDumps/dump_$now 2> /dev/null
            mv dump  ~/Desktop/LoomaMongoDumps/dump_$now
        fi

echo " - - creating new mongodump 'dump'"
echo "************************************"

mongodump --quiet --db looma

echo ' - - archiving Looma (code) to rsync.net'
echo "************************************"
cd   /usr/local/var/www/Looma		# cd to Looma/ (on a MAC)

RW="58189@usw-s008.rsync.net"

SECONDS=0

### should exclude content/chapters folders for now so that Looma II's in the field wont run out of storage space
###
###   this code not tried yet
###
###    cd /var/local/var/www
###    excludes='/content/chapters/'
###    rsync ... ... --exclude $excludes ... ...
###
##############
# sync code to rsync.net  [excluding "." files like .git/]
if [[ $1 = "dryrun" ]]
then
    echo "NOTE: dryrun"

     #EXAMPLE chmod: --chmod=Dg+s,ug+w,Fo-w,+X

     #removed "--include '.ssh'"
    rsync -avz  --dry-run --delete --perms --chmod=u+rwx,go+rx --update --progress  --exclude ".[!.]*" --delete-excluded -e "ssh -i ~/.ssh/id_rsa" /usr/local/var/www/Looma  $RW:
    echo "FINISHED dryrun"
else
   timestamp "/usr/local/var/www/Looma"

    echo " - - new timestamp for code is $(cat /usr/local/var/www/Looma/archivetimestamp.txt)"
    echo "************************************"

   rsync -avz            --delete --perms --chmod=u+rwx,go+rx --update --progress   --exclude ".[!.]*" --delete-excluded -e "ssh -i ~/.ssh/id_rsa" /usr/local/var/www/Looma  $RW:
fi
result $?
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds elapsed."

echo "************************************"
echo -n "archive CONTENT files? [y/n]"
read userchoice
if [[ $userchoice = "n" ]]
  then
    exit 1
  fi

echo "************************************"
echo 'archiving Looma (content) to rsync.net'
echo "************************************"
echo
cd /usr/local/var/www/content		        # cd to content/ (on a MAC)
SECONDS=0

if [[ $1 = "dryrun" ]]
then
    echo "NOTE: dryrun"
    rsync -avz  --dry-run --delete --perms --chmod=u+rwx,go+rx --update    --exclude ".[!.]*" --delete-excluded  -e "ssh -i ~/.ssh/id_rsa" /usr/local/var/www/content  $RW:
    echo "FINISHED dryrun"
else
    timestamp "/usr/local/var/www/content"

    echo "new timestamp for content is "
    cat "/usr/local/var/www/content/archivetimestamp.txt"

    rsync -avz            --delete --perms --chmod=u+rwx,go+rx --update   --exclude ".[!.]*" --delete-excluded -e "ssh -i ~/.ssh/id_rsa" /usr/local/var/www/content  $RW:
fi
result $?
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds elapsed."

echo "*********************************************"
echo " - - DONE updating Looma archive on rsync.net"
echo "*********************************************"
