#!/bin/bash
#
#  filename: clearChromiumCache
#       author: skip
#       date:   Jun 2019
#
#  ~/.config/chromium holds the user profile - we dont need to delete this
#
# ~/.cache/chromium holds the chromium cache - pages visited in Default/Cache, media loaded in Default/MediaCache
#  we delete these cache items when loading a new Looma image so the old cached items arent used

if [ -d ~/.cache/chromium/Default ]
  then
          rm -r ~/.cache/chromium/Default
  fi

# on newer Loomas, Chromium is installed by SNAP and uses different cache locations


if [ -d ~/snap/chromium/common/chromium/Default ]
  then
          rm -r ~/snap/chromium/common/chromium/Default/Cache
  fi