#!/bin/bash
#
#  filename: loomaUSB
#   VERSION: 2.0
#       put this file in /usr/local/bin on each looma
#       with chmod +x to make it executable
#
#       this file just calls /var/www/html/Looma/looma schell scripts/loomaUSBer
#       this allows us to 'update' the USB script using the normal sync from S3
#
#       author: skip
#       date:   Jun 2019
echo "*****************************************************"
echo " - - - UPDATING a USB memory stick from Amazon - - - "
echo "*****************************************************"
source "/var/www/html/Looma/looma shell scripts/loomaUSBer"
echo "*****************************************************"
