#!/bin/bash
#
#  filename: loomaupdater
#       VERSION 7.0
#       author: skip
#       date:   SEP 2021, OCT 2023, FEB 2024, MAY 2024, OCT 2025
#
#     revised OCT 2025 to add option to sync with "preview" version of Looma
#     revised OCT 2023 to check 'archivetimestamp.txt' to see if an update is needed
#       on both /Looma and /content
#
#  used to update a pre-installed Looma by installing latest code, database & content
#           only changed or brand new files are transferred
#
#   source files to be updated may be
#    - on a USB stick at /media/odroid/LOOMA/loomaupdate (the "U" option)
#    - or, on the Internet at rsync.net (the "I" option)
#
#   file structure expected if on the USB:
#
#       Looma/               (full set of new Looma code)
#       Looma/mongo-dump/dump/looma/   (latest mongodump of the new database content)
#       content/*   (folders with new content)
#                   (these are usually NEW folders,
#                      but this can be used to overwrite existing content folders)
#    optionally other content folders by uncommenting code below, like
#       maps2018/*
#       ePaath/*
#    or other content folders
#
#   steps performed:
#.      set proper directory to download to
#       sync newer code files into existing Looma code
#       use mongorestore to load new data into the existing mongo database
#                  (merging into some collections, like 'lessons' and 'text-files')
#       sync newer content files into "content" directory
#
#       CALL with "loomaupdate [dryrun] [preview]
#           optional arg "dryrun" for testing the script without actually changng files
#           optional arg "preview" for synching with the PREVIEW version instead of RELEASE version of Looma

#RSYNC options used:

# -rtvz     recursive, set modification time, verbose, use compression
# --progress, --update, --delete, --no-perms
# --chmod=ugo=rwX
# --chown=looma:looma. NOT USED - files get 58198:58198 on Update Server, then get odroid:odroid on Looma's that download from the update server
# optional: --dry-run
# --include ".ssh/"  --exclude ".[!.]*" --exclude "vendor/" --exclude "composer*"


checksudo() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "This script must be run as root. Please run again using 'sudo loomaupdate'"
        exit 1
    fi
}   #  end checksudo()

# display result of previous  command
result () {
    if [[ $1 -ne 0 ]]
    then
        echo "****************************************************************"
        echo "ERROR: previous operation returned $1"
    else
        echo "****************************************************************"
        echo "operation successful"
    fi
}  #  end result()

pause () {
   echo " Paused $1"
   read -p "     press [Enter] to continue"
}  #  end pause()

backup () {
    echo
    echo "****************************************************************"
    echo "- preparing to backup current LOOMA CODE to LoomaBAK"
    echo "-   *** usually it is OK to skip this step to save time"
    echo -n  "- - continue ('n' recommended) [y/n]?"; read input;
    if [[ $input = "y" ]]
    then
        if [ -d "/var/www/html/LoomaBAK" ]
        then
          echo "- deleting old LoomaBAK directory"
          sudo rm -r "/var/www/html/LoomaBAK"
          result $?
        fi
        mv    "/var/www/html/Looma"   "/var/www/html/LoomaBAk"
        result $?
    else
        echo " - - - SKIPPED: backing up Looma code "
    fi
}  #  end backup()


# ///////////////////////////////////////////////////////////
# /////////////     checknetworkspeed ()    /////////////////
# ///////////////////////////////////////////////////////////
checknetworkspeed () {
  # test internet presence and speed
    echo "************************************"
    echo "Testing network connection and speed"
    echo "************************************"
    echo
    t=$(date +%s)
    wget ftp://speedtest.tele2.net/10MB.zip -O /dev/null > /dev/null
    r=$?
    s=$(date +%s)
    if [[ $r -ne 0 ]]
    then
        echo "****************************************************************"
        echo "no internet connection found";exit $r;
    else
        echo "****************************************************************"
        echo -n "Internet speed is MB/s: ";expr 8 \* 10 / $(($s - $t))
        echo -n  "- - continue at this speed [y/n]?"; read input;
        if [[ $input != "y" ]]
        then
            exit 1
        fi
    fi
}  #  end checknetworkspeed()

# ///////////////////////////////////////////////////////////
# /////////////     checktimestamp ()    /////////////////////
# ///////////////////////////////////////////////////////////
# return 1 if timestamps are equal [so no update is needed]
checktimestamp () {         # call with
#                           $1 = destination directory to check for timestamp [/var/www/html/content or /var/www/html/Looma]
#                           $2 = source url to check for timestamp
#                           $3 = 'Looma' or 'content'

# echo "in checktimestamp(): source path is $2, source dir is $3, source file is ${3}/archivetimestamp.txt"
# get timestamp of files currently on this Looma
  if [[ -f $1/$3/archivetimestamp.txt ]]
   then
     current=`cat "$1/$3/archivetimestamp.txt"`
   else
     current="none"
   fi

# get timestamp of files on Looma Archive Server
  if [[ $source = "I" ]]
  then
      if [[ `which sshpass` != "" ]]
      then
        latest=`sshpass -p looma ssh $2 cat "${3}/archivetimestamp.txt"`
      else
        echo "enter password 'looma' if requested"
        latest=`ssh  $2 cat "${3}/archivetimestamp.txt"`
      fi
  else
     latest=`cat "${2}/${3}/archivetimestamp.txt"`
  fi

# check if timestamps are equal
    echo " - - Current timestamp for $3 is    $current"
    echo " - - Latest timestamp for archive is $latest"
    if [[ $current = "$latest" ]]
    then
        return 1
    else
        return 0
    fi
}  #  end checktimestamp()

# ///////////////////////////////////////////////////////////
# /////////////     DOSYNC()    /////////////////
# ///////////////////////////////////////////////////////////
# function DOSYNC() to exec the rsync.
# global var $DRYRUNMODE is either "--dry-run" or ""
# call dosync() with:
#       $1 = "source"
#       $2 = "destination"
#       and [optional] $3 = "--sizeonly" or null

dosync () {

    SOURCE=$1
    DESTINATION=$2
    SIZEONLY=$3

    # RSYNC_PASSWORD avoids manual entry of password for rsync (but, doesnt work?)
    # RSYNC_PASSWORD="looma"
    echo "**********************************";

 if [[ $DRYRUNMODE = "--dry-run" ]]
    then
      echo "in dosync(): doing RSYNC from $SOURCE to $DESTINATION with --dry-run [no changes will be made]"
    else
      echo "in dosync(): doing RSYNC from $SOURCE to $DESTINATION"
 fi
    echo
    #echo "  *** *** if prompted for \"password:\" enter \"looma\"  *** ***"

    if [[ `which sshpass` != "" ]]
      # NOTE, adding "O" option to avoid errors with modified date updates
    then
    sshpass -p 'looma' \
        rsync -rtvz  $DRYRUNMODE $SIZEONLY  \
        --stats  --times \
        --perms --owner --group --chown=odroid:odroid --chmod=u+rwX,go+rX  \
        --include ".ssh/"  --exclude ".[!.]*" --exclude "vendor/" --exclude "composer*" \
        -e "ssh"   \
       $SOURCE  $DESTINATION
      # NOTE: RSYNC needs a slash after FROM dir and no slash after TO dir
    returncode=$?
     # NOTE, could try adding "O" option ["oh", not "zero"] to avoid errors with modified date updates
    else
      echo "enter password 'looma' if requested"
        rsync -rtvz  $DRYRUNMODE $SIZEONLY  \
        --stats  --times \
        --perms --owner --group --chown=odroid:odroid --chmod=u+rwX,go+rX  \
        --include ".ssh/"  --exclude ".[!.]*" --exclude "vendor/" --exclude "composer*" \
        -e "ssh"   \
       $SOURCE  $DESTINATION
      # NOTE: RSYNC needs a slash after FROM dir and no slash after TO dir
      returncode=$?
    fi

  if [[ $DRYRUNMODE != "--dry-run"  && $returncode = 0 ]]
  then
     echo
     echo "**************************"
     echo "setting $DESTINATION/archivetimestamp.txt to $latest [`date -r $latest`]"
     echo $latest > $DESTINATION/archivetimestamp.txt
     echo
 fi

 if [[ $returncode != 0 ]]
 then
     echo "looma update 'rsync' operation from $SOURCE failed with error $returncode. rerun 'loomaupdate' later"
     exit
 fi
}  #  end dosync()

# ///////////////////////////////////////////////////////////
# /////////////     start of main code      /////////////////
# ///////////////////////////////////////////////////////////

checksudo       # warn and quit if not running in 'sudo'

echo
echo "****************************************************************"
echo "START LOOMA UPDATE: updating Looma code, database and content"
echo "****************************************************************"
echo "this a DANGEROUS operation and can disable a Looma"
echo "Be sure you have read the instructions"
echo "****************************************************************"


if [[ "$1" = "dryrun" || "$2" == "dryrun" ]]
  then
    DRYRUNMODE="--dry-run"
  else
    DRYRUNMODE=""
fi

contenttime=0
codetime=0

#####################
##################### user input - choose update from USB stick or from Internet
#####################
echo; echo "****************************************************************"
echo "- Update using Internet connection or USB memory?"
echo -n  "- -enter  U for USB, I for internet [I/U]?"; read source

if [[ $source = "U" ]]
then

########################################
###########################  sourcing from USB - settings  #############

  SOURCE_PREFIX="/media/odroid/LOOMA/loomaupdate/"   # for Linux (different for MAC)

      echo; echo "****************************************************************"
      echo "    you must insert a USB memory stick which is named LOOMA"
      echo "    be sure the USB filesystem format is FAT32 or exFAT    [*** not NTFS ***]"
      echo "    the USB stick must have the files to be uploaded stored in a top-level folder named 'loomaupdate' "
      echo "****************************************************************"

      cd /media/odroid/LOOMA/loomaupdate

      if [ "$?" -ne 0 ]
      then
          echo; echo "ERROR: couldn't find LOOMA/loomaupdate directory on USB"
          exit 1
      fi

      echo
      echo -n  "- using this directory to get new files: ";pwd
      echo

########################################
###########################  sourcing from the Internet-  settings ###############

  elif [[ $source = "I" ]]
  then
      # URL for rsync.net Looma Archive Server
     SOURCE_URL="58191@usw-s008.rsync.net"

	if [[ "$1" = "preview" || "$2" == "preview" ]]
	  then
	      SOURCE_PREFIX="${SOURCE_URL}:../preview/"
	  else
	      SOURCE_PREFIX="${SOURCE_URL}:../"
	fi

    echo; echo "****************************************************************"
    echo "-   *** you can check network speed before proceeding"
    echo -n  "- - check and report network speed [y/n]?"; read input;
    if [[ $input = "y" ]]
    then
      checknetworkspeed
    fi
  else
      echo; echo "****************************************************************"
      echo 'ERROR: input must be "U" or "I"'
      echo "****************************************************************"
      exit 1
  fi

########################### set the target directory ###############E

echo "********************"


   if [ ! -d /var/www/html/Looma ];
     then
       echo "Target directory does not contain a /Looma folder"
       exit
    fi

###############  do the transfers ###############
#################################################
    #       copy current Looma code to LoomaBAK
    #       NOTE: call to function DACKUP() commented out for now to save time
    # backup

    checktimestamp "/var/www/html"  ${SOURCE_URL} "Looma"

    if [[ $? = 1 ]]
      then
        echo "++++++++++++++++++++++++"
        echo "/var/www/html/Looma is UP TO DATE [No files  will be transferred]"
        echo "++++++++++++++++++++++++"
      else

       #       install new Looma code
        echo
        echo "****************************************************************"
        echo "- preparing to update LOOMA CODE"
        echo -n  "- - continue ('y' recommended) [y/n]?"; read input;
        if [[ $input = "y" ]]
        then

        SECONDS=0
        echo
        echo "starting to update code files. please wait ..."
        echo

        #### calling DOSYNC() ##########
        dosync "${SOURCE_PREFIX}Looma/"   "/var/www/html/Looma"

        echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds elapsed."
        codetime=$SECONDS

          if [[ -d "/var/www/html/Looma/mongo-dump/dump/looma" && "$DRYRUNMODE" != "--dry-run" ]]
                then
                    echo
                    echo "starting to update Looma's database. please wait ..."
                    echo

                      if which mongo
                      then
                         mongo --quiet --eval "db.dropDatabase();" looma
                      elif which mongosh
                      then
                         mongosh --quiet --eval "db.dropDatabase();" looma
                      fi

                    #mongosh --quiet --eval "db.dropDatabase();" looma

                    mongorestore --quiet --db looma "/var/www/html/Looma/mongo-dump/dump/looma/"

                    if [[ -f /var/www/html/Looma/mongo-dump/logins/defaultlogins.json ]]
                    then
                       mongoimport --quiet --db loomausers --collection logins  --mode upsert --upsertFields name --file "/var/www/html/Looma/mongo-dump/logins/defaultlogins.json"
                       rm "/var/www/html/Looma/mongo-dump/logins/defaultlogins.json"
                    fi
                else echo "ERROR: no source dir (/var/www/html/Looma/mongo-dump/dump/looma) found for mongo restore"
                fi
        else
            echo " - - - SKIPPED: installing new Looma code"
        fi
   fi

#################################################
    #       copy new files into "content" directory
#################################################

        ########## NOTE: content always comes from ../content. there is no separate ../preview/content folder

    checktimestamp "/var/www/html"  ${SOURCE_URL} "content"

    if [[ $? = 1 ]]
      then
        echo "++++++++++++++++++++++++"
        echo "/var/www/html/content is UP TO DATE [No files will be transferred]"
        echo "++++++++++++++++++++++++"
      else
        echo
        echo "****************************************************************"
        echo "- preparing to update files in CONTENT directory"
        echo -n  "- - continue ('y' recommended) [y/n]?"; read input;
        if [[ $input = "y" ]]
        then
           SECONDS=0

            #  for CONTENT calling dosync() with $4 (size-only) = "--size-only"
            echo
            echo "starting to update content files. this takes a long time. please wait ..."
            echo
            #### calling DOSYNC() ##########
            dosync "${SOURCE_URL}:../content/" "/var/www/html/content" "--size-only"

            echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds elapsed."
            contenttime=$SECONDS
        else
            echo " - - - SKIPPED: installing new Looma content"
        fi
  fi

  echo "*****************************************"
  echo "Total $(( ($contenttime + $codetime) / 60)) minutes and $(( ($contenttime + $codetime)  % 60)) seconds elapsed."

echo "*****************************************"
echo
echo "  deleting browser cache";
if [ -d "/home/odroid/snap/chromium/common/chromium/Default/Cache" ]; then
  rm -rf "/home/odroid/snap/chromium/common/chromium/Default/Cache"
fi
#rm -R /home/odroid/snap/chromium/common/chromium/Default/Cache
echo

echo "****************************************************************"
echo "****************************************************************"
 if [[ $DRYRUNMODE = "--dry-run" ]]
 then
    echo "DONE - LOOMA UPDATE DRY RUN:  no files were changed"
 else
    echo "DONE - LOOMA UPDATE: updating Looma code, database and content"
 fi
echo "****************************************************************"
echo "****************************************************************"
echo

