#!/bin/bash
#
#  filename: loomaupdate
#  VERSION 2.0
#       author: skip
#       date:   Jan-jun 2019
#
#  used to update a pre-installed Looma by installing new code, database & content
#
#   files to be updated may
#    - be on a USB stick at /media/odroid/LOOMA/loomaupdate (the "U" option)
#    - or, on Amazon S3 (the "I" option)
#
#   file structure expected if on the USB:
#
#       Looma/               (full set of new Looma code)
#       Looma/mongo-dump/dump/looma/   (latest mongodump of the new database content)
#       content/*   (folders with new content)
#                   (these are usually NEW folders,
#                      but this can be used to overwrite existing content folders)
#    possibly other content folders, like
#       maps2018/*
#       ePaath/*
#    or other content folders
#
#   steps performed:
#       sync new code files into existing Looma code
#          [or backup existing Looma code to LoomaBAK and replace fully with new code
#       use mongorestore to load new data into the existing mongo database
#       sync new content files into "content" directory

result () {
    if [[ $1 -ne 0 ]]
    then
        echo "****************************************************************"
        echo "ERROR: previous operation returned $1"
    else
        echo "****************************************************************"
        echo "operation successful"
    fi
}

#
echo
echo
echo "****************************************************************"
echo "START LOOMA UPDATE: updating Looma code, database and content"
echo "****************************************************************"
echo "this a DANGEROUS operation and can disable a Looma"
echo "Be sure you have read the instructions"
echo "****************************************************************"
echo

echo "****************************************************************"
echo "- Update using Internet connection or USB memory?"
echo -n  "- -enter  U for USB, I for internet [I/U]?"; read input

if [[ $input = "U" ]]
then
##########################
# start of USB section
##########################

    echo "****************************************************************"
    echo "    you must insert a USB memory stick which is named LOOMA"
    echo "    be sure the USB filesystem format is FAT32    [*** not NTFS ***]"
    echo "    the USB stick must have the files to be uploaded stored in a top-level folder named 'loomaupdate' "
    echo "****************************************************************"

    cd /media/odroid/LOOMA/loomaupdate # for Linux (different for MAC)

    if [ "$?" -ne 0 ]
    then
        echo "ERROR: couldn't find LOOMA/loomaupdate directory on USB"
        exit 1
    fi

    echo
    echo -n  "- using this directory to get new files: ";pwd
    echo

    #       copy current Looma code to LoomaBAK
    echo "- preparing to backup current Looma code to LoomaBAK"
    echo "-   *** usually it is OK to skip this step to save time"
    echo -n  "- - continue ('n' recommended) [y/n]?"; read input;
    if [[ $input = "y" ]]
    then
        if [ -d /var/www/html/LoomaBAK ]
        then
            rm -r /var/www/html/LoomaBAK
        fi
        mv    /var/www/html/Looma   /var/www/html/LoomaBAk
        result $?
    else
        echo " - - - SKIPPED: backing up Looma code "
    fi

    #       install new Looma code
    echo
    echo "- preparing to install new Looma code"
    echo -n  "- - continue ('y' recommended) [y/n]?"; read input;
    if [[ $input = "y" ]]
    then
        #*************RSYNC*********************
        #NOTE: slash after "Looma/" and no slash after "/var/www/html/Looma"
        if [[ $1 = "dryrun" ]]
        then
            rsync   --dry-run --recursive --verbose --times --stats --progress Looma/ /var/www/html/Looma
            result $?
        else
            rsync             --recursive --verbose --times --stats --progress Looma/ /var/www/html/Looma
            result $?
        fi

        #clear browser cache so the new code files will be used
        source "/var/www/html/Looma/looma shell scripts/loomaClearChromiumCache"
    else
        echo " - - - SKIPPED: installing new Looma code"
    fi

    #       install new Looma database
    echo
    echo "****************************************************************"
    echo "- preparing to update Looma database"
    echo "-   ***note: this will not erase any lesson plans installed in the database"
    echo -n  "- - continue ('y' recommended) [y/n]?"; read input;

    if [[ $input = "y" ]]
    then
        if [[ -d /media/odroid/LOOMA/loomaupdate/Looma/mongo-dump/dump/looma ]]
        then

        ####ADD code here to db.version_number  .drop() so that version # will be updated in mongo

            # install new db changes into existing db
            mongorestore --quiet --db looma /media/odroid/LOOMA/loomaupdate/Looma/mongo-dump/dump/looma/
            result $?
        else echo "ERROR: no source dir (/media/odroid/LOOMA/loomaupdate/Looma/mongo-dump/dump/looma) for mongo restore"
        fi
    else
        echo " - - - SKIPPED: installing new Looma database"
    fi

    #       copy new files into "content" directory
    echo
    echo "- preparing to copy new files into content directory"
    echo -n  "- - continue ('y' recommended) [y/n]?"; read input;
    if [[ $input = "y" ]]
    then
        if [ -d "content" ]
        then
             if [[ $1 = "dryrun" ]]
            then
                rsync  --dry-run -r --stats content/  /var/www/html/content   #NOTE: slash after "content/" and no slash after "/var/www/html/content"
                result $?
            else
                rsync             -r --stats content/  /var/www/html/content   #NOTE: slash after "content/" and no slash after "/var/www/html/content"
                result $?
            fi
        fi

        if [ -d "maps2018" ]
        then
            if [[ $1 = "dryrun" ]]
            then
                rsync --dry-run -r maps2018/ /var/www/html/maps2018  #NOTE: slash after "source/" and no slash after "/var/www/html/maps2018"
                result $?
            else
                rsync            -r maps2018/ /var/www/html/maps2018  #NOTE: slash after "source/" and no slash after "/var/www/html/maps2018"
                result $?
            fi
        fi
        if [ -d "ePaath" ]
        then

            if [[ $1 = "dryrun" ]]
                then
                    rsync --dry-run -r ePaath/   /var/www/html/maps2018  #NOTE: slash after "source/" and no slash after "/var/www/html/ePaath"
                    result $?
                else
                    rsync            -r ePaath/   /var/www/html/ePaath  #NOTE: slash after "source/" and no slash after "/var/www/html/ePaath"
                    result $?
                fi

        fi
    else
        echo " - - - SKIPPED: installing new Looma content"
    fi
# end of USB section


##########################
# start Internet section
##########################

elif [[ $input = "I" ]]
then
    # test internet presence and speed
    echo "************************************"
    echo "Testing network connection and speed"
    echo "************************************"
    echo
    t=$(date +%s)
    sudo wget ftp://speedtest.tele2.net/10MB.zip -O /dev/null
    r=$?
    s=$(date +%s)
    if [[ $r -ne 0 ]]
    then
        echo "no internet connection found";exit $r;
    else
        echo "****************************************************************"
        echo -n "Internet speed is MB/s: ";expr 8 \* 10 / $(($s - $t))
        echo -n  "- - continue at this speed [y/n]?"; read input;
        if [[ $input != "y" ]]
        then
            exit 1
        fi
    fi

    #       copy current Looma code to LoomaBAK
    echo
    echo "- preparing to backup current Looma code to LoomaBAK"
    echo "-   *** usually it is OK to skip this step to save time"
    echo -n  "- - continue ('n' recommended) [y/n]?"; read input;
    if [[ $input = "y" ]]
    then
        if [ -d /var/www/html/LoomaBAK ]
        then
            echo "- deleting old LoomaBAK directory"
            sudo rm -r /var/www/html/LoomaBAK
            result $?
        fi
        sudo mv    /var/www/html/Looma   /var/www/html/LoomaBAK
        result $?
    else
        echo " - - - SKIPPED: backing up Looma code "
    fi

    #       install new Looma code
    echo
    echo "- preparing to install new Looma code"
    echo -n  "- - continue ('y' recommended) [y/n]?"; read input;
    if [[ $input = "y" ]]
    then
       # sync Looma (code)

        if [[ $1 = "dryrun" ]]
        then
            aws s3 sync --dry-run --no-sign-request s3://villagetech.looma/Looma /var/www/html/Looma
            result $?
        else
            aws s3 sync            --exact-timestamps --no-sign-request --no-verify-ssl --exclude "*.git/*" s3://villagetech.looma/Looma /var/www/html/Looma
            result $?
        fi

        #clear browser cache so the new files will be used
        source "/var/www/html/Looma/looma shell scripts/loomaClearChromiumCache"

        #       install new Looma database
        echo
        echo "- preparing to update Looma database"
        echo -n  "- - continue ('y' recommended) [y/n]?"; read input;

        if [[ $input = "y" ]]
        then
            if [[ -d /var/www/html/Looma/mongo-dump/dump/looma ]]
            then
                # mongo loomaBAK  --eval "db.dropDatabase()"               # remove old BAK
                # mongo looma --eval "db.copyDatabase('looma','loomaBAK')" # backup current db
                # mongo looma --eval "db.dropDatabase()"                   # remove current db
                mongorestore --quiet --db looma /var/www/html/Looma/mongo-dump/dump/looma/       # install new db changes into existing db
                result $?
            else echo "ERROR: no source dir (/var/www/html/Looma/mongo-dump/dump/looma) for mongo restore"
            fi
        else
            echo " - - - SKIPPED: update Looma database"
        fi


    else
        echo " - - - SKIPPED: installing new Looma code"
    fi


    #       copy new files into "content" directory
    echo
    echo "- preparing to copy new files into content directory"
    echo -n  "- - continue ('y' recommended) [y/n]?"; read input;
    if [[ $input = "y" ]]
    then
        if [[ $1 = "dryrun" ]]
            then
                aws s3 sync --dry-run --no-sign-request s3://villagetech.looma/content /var/www/html/content
                result $?
            else
                aws s3 sync            --exact-timestamps --no-sign-request --no-verify-ssl s3://villagetech.looma/content /var/www/html/content
                result $?
            fi

        #aws s3 sync --dry-run --no-sign-request s3://villagetech.looma/maps2018 /var/www/html/maps2018
        #aws s3 sync --dry-run --no-sign-request s3://villagetech.looma/ePaath /var/www/html/ePaath
    else
        echo " - - - SKIPPED: installing new Looma content"
    fi

# end of Internet section
else
    echo "****************************************************************"
    echo 'ERROR: input must be "U" or "I"'
    echo "****************************************************************"
    exit 1
fi

echo
echo "****************************************************************"
 if [[ $1 = "dryrun" ]]
 then
    echo "DONE - LOOMA UPDATE DRY RUN:  no files were changed"
 else
    echo "DONE - LOOMA UPDATE: updating Looma code, database and content"
 fi
echo "****************************************************************"
echo
echo
echo

