#!/bin/bash
#
#  filename: loomaUSBer
#       VERSION 2.0
#       author: skip
#       date:   JUN 2019
#
#   called from shell script "loomaUSB" which is in /usr/local/bin (must be executable)
#   that script uses "source" command to load this file
#
#  used to update a USB memory stick frm the 'archive' version of Looma on AWS S3, including new code, database & content
#
#   loomaUSB can be called with a parameter "dryrun" in which case the transfers from AWS are nt performed, but dry run instead
# using AWS CLI command “sync” updates all changed files
# from Amazon S3 to the USB

# prerequisite:
#        AWS CLI package of S3 commands installed on the receiving computer (with the USB stick)
#        sudo apt-get install awscli

# using AWS CLI command “sync” downloads all changed or more recent files
# from Amazon S3 to a USB stick

result () {
    if [[ $1 -ne 0 ]]
    then
        echo "****************************************************************"
        echo "ERROR: previous operation returned $1"
    else
        echo "****************************************************************"
        echo "operation successful"
    fi
}

echo "********************************************************"
echo " Looma - update a USB memory stick"
echo "    copies new or modified files from Amazon S3 to a USB"
echo "*******************************************************"
echo

   # test internet presence and speed
#    echo "************************************"
#    echo "Testing network connection and speed"
#    echo "************************************"
#    echo
#    t=$(date +%s)
#    sudo wget ftp://speedtest.tele2.net/10MB.zip -O /dev/null
#    r=$?
#    s=$(date +%s)
#    if [[ $r -ne 0 ]]
#    then
#        echo "no internet connection found";exit $r;
#    else
#        echo "****************************************************************"
#        echo -n "Internet speed is MB/s: ";expr 8 \* 10 / $(($s - $t))
#        echo -n  "- - continue at this speed [y/n]?"; read input;
#        if [[ $input != "y" ]]
#        then
#            exit 1
#        fi
#    fi


cd /media/odroid/LOOMA
if [[ `pwd` != '/media/odroid/LOOMA' ]]
    then
        echo
        echo "***********ERROR***********************************"
        echo "  Didnt find USB memory at /media/odroid/LOOMA"
        echo "  Be sure the USB is inserted and its name is LOOMA"
        echo "***************************************************"
        exit 1
    fi

mkdir -p loomaupdate/Looma     #in case its not already there
mkdir -p loomaupdate/content   #in case its not already there

cd loomaupdate

echo
echo "**************************************************"
echo "- preparing to update Looma code on the USB memory"
echo -n  "- - continue [y/n]?"; read input;

if [[ $input = "y" ]]
then
    if [[ $1 = "dryrun" ]]
    then
        aws s3 sync --dryrun --exact-timestamps --no-sign-request --no-verify-ssl s3://villagetech.looma/Looma Looma   # note, no "/" after content
        result $?
    else
        aws s3 sync          --exact-timestamps --no-sign-request --no-verify-ssl s3://villagetech.looma/Looma Looma   # note, no "/" after content
        result $?
    fi
fi

echo
echo "*****************************************************"
echo "- preparing to update Looma content on the USB memory"
echo -n  "- - continue [y/n]?"; read input;

if [[ $input = "y" ]]
then
    if [[ $1 = "dryrun" ]]
    then
        aws s3 sync --dryrun --exact-timestamps --no-sign-request s3://villagetech.looma/content content   # note, no "/" after content
        result $?
    else
        aws s3 sync          --exact-timestamps --no-sign-request s3://villagetech.looma/content content   # note, no "/" after content
        result $?
    fi
fi
echo
echo "****************************************************************************"
echo "DONE LOOMA UPDATE: updating USB memory with Looma code, database and content"
echo "****************************************************************************"
echo
