#!/bin/bash
cd '../../content/Wikipedia for Schools/wp/index/'
pwd

while read -r line  || [[ -n "$line" ]]; do

    REGEX='\/wp\/.\/(.*)"\>(.*)\<'
    if [[ $line =~ $REGEX ]]; 
    then 
        activity=${BASH_REMATCH[1]}  
        echo "activity is: " $activity
    fi  
done < subject.Mathematics.htm